---

# Copyright 2022 (c) José Ángel de Bustos Pérez 
#   Author: José Ángel de Bustos Pérez <jadebustos@gmail.com>
#
# This file is part of the IdM workshop.
#
# This workshop is free software: you can redistribute it and/or modify it under the terms of 
# the GNU General Public License v3 as published by the Free Software Foundation.
# This workshop is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
# See the GNU General Public License v3 for more details.

# You should have received a copy of the GNU General Public License v3 along with the IdM workshop. 
# If not, see https://www.gnu.org/licenses/gpl-3.0.en.html.

# create users's password hash and store it in a variable
- name: generate sha512 password hashes
  ansible.builtin.shell: "/usr/bin/openssl passwd -6 -salt $(/usr/bin/openssl rand -base64 48) {{ item.value.password }}"
  register: sha512
  with_dict:
    - "{{ users }}"

#- name: display sha512
#  ansible.builtin.debug: var=sha512

#- name: show sha512.results
#  ansible.builtin.debug: var=item.stdout
#  loop:
#    - "{{ sha512.results }}"

# create a dictionary where the key is the username and the value is password's hash
# to see sha512 structure you can uncomment the two above tasks
- name: create a dictionary with password hashes
  set_fact:
    passwdhashes: "{{ passwdhashes|default({}) | combine( {item.item.key: item.stdout} ) }}"
  loop: "{{ sha512.results }}"

# uncomment this task to see passwordhasses structure
#- name: display passwordhashes
#  ansible.builtin.debug: var=passwdhashes

# configure user's passwords
- name: change shadow password hash
  ansible.builtin.user:
    user: "{{ item.key }}"
    password: "{{ item.value }}"
  become: yes
  with_dict:
    - "{{ passwdhashes }}"