---
# Copyright 2022 (c) José Ángel de Bustos Pérez 
#   Author: José Ángel de Bustos Pérez <jadebustos@gmail.com>
#
# This workshop is free software: you can redistribute it and/or modify it under the terms of 
# the GNU General Public License v3 as published by the Free Software Foundation.
# This workshop is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
# See the GNU General Public License v3 for more details.

# You should have received a copy of the GNU General Public License.
# If not, see https://www.gnu.org/licenses/gpl-3.0.en.html.

- hosts: all
  gather_facts: true

  tasks:
    - name: identify first free disk
      set_fact:
        disks: "/dev/{{ item.key }}"
      when:
        # if disk has no partitions the following vars will be emptied
        - not item.value.partitions
        - not item.value.holders
        - not item.value.links.uuids
        - not item.value.links.labels
        # disk devices will be /dev/vd? or /dev/sd?
        - item.key | regex_search ("vd|sd")
      loop: "{{ ansible_devices  | dict2items }}"

    - name: show free disk
      debug: msg="Free disk {{ disks }}"