---

# Copyright 2022 (c) José Ángel de Bustos Pérez 
#   Author: José Ángel de Bustos Pérez <jadebustos@gmail.com>
#
# This file is part of the IdM workshop.
#
# This workshop is free software: you can redistribute it and/or modify it under the terms of 
# the GNU General Public License v3 as published by the Free Software Foundation.
# This workshop is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
# See the GNU General Public License v3 for more details.

# You should have received a copy of the GNU General Public License v3 along with the IdM workshop. 
# If not, see https://www.gnu.org/licenses/gpl-3.0.en.html.


- hosts: localhost
  gather_facts: false
  vars_prompt:

    # ask to wirte a password and it is stored in a variable
    # using private we can control if the password can be viewed on the screen or not
    # with this particular configuration the password will not be shown on the screen
    - name: password
      prompt: "Write you password to get the password hash: "
      private: yes

  tasks:

    # random value to be used as salt to create the password and it will be stored in a variable
    # using delegate_to means that this task will be run on the localhost
    - name: random value to be used as salt to create the password
      command: /usr/bin/openssl rand -base64 32
      register: random_pass
      delegate_to: 127.0.0.1

    - name: hash creation (sha512)
      command: "/usr/bin/openssl passwd -6 -salt {{ random_pass.stdout }} {{ password }}"
      register: password_sha512
      delegate_to: 127.0.0.1

    - name: debug
      debug: msg="Password hash is {{ password_sha512.stdout }}"
      delegate_to: 127.0.0.1

